### PR TITLE
2134-merge_simplification

### PR DESCRIPTION
**Pull request by ohibo**
## Pre-review checklist

I have ensured that:

- [ ] Code runs successfully in the development environment.
- [ ] New code is tested to prove that it works. If not, justify reasoning.
- [ ] New code is documented using [type hinting](https://realpython.com/lessons/type-hinting/) and following the [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) docstring format.
- [ ] New code follows the project naming standards.

## Post-review checklist

As I merge these changes, I have:

- [ ] Updated the related Jira ticket, including approximate time spent (including review).
- [ ] Moved the related Jira ticket to Done.

### CODE REVIEW

**Comment by ohibo** [comment]
For swabs, substitute the swab merge ETL stage for the following 4 substages

  - function: merge_swab_ETL_a
    run: False
    swab_table: pcr_test_results
    survey_responses_table: merged_responses_antibody_data
    swab_files_to_exclude: []


  - function: merge_swab_ETL_b
    run: False
    outter_joined_table: outter_joined_table


  - function: merge_swab_ETL_c
    run: True
    table_to_validate: outter_joined_xtox_table


  - function: merge_swab_ETL_d
    run: False
    input_table: validated_table
    swab_output_tables: [
      "merged_responses_antibody_swab_data",
      "swab_merge_residuals",
      "swab_merge_failed_records",
    ]

**Comment by ohibo** [comment]
# Antibody ---------------------------------------------
  - function: merge_blood_ETL_a # R3
    run: False
    input_antibody_table: joined_blood_test_data
    input_survey_responses_table: post_union_transformed_survey_responses
    blood_files_to_exclude: []
    output_joined_table: outter_joined_antibody_table
    

  - function: merge_blood_ETL_b # R3
    run: False
    input_joined_table: outter_joined_antibody_table
    output_xtox_flagged_table: joined_xtox_antibody_table


  - function: merge_blood_ETL_c # R3
    run: False
    input_table_to_validate: joined_xtox_antibody_table
    output_validated_table: validated_antibody_table


  - function: merge_blood_ETL_d # R3
    run: True
    input_table: validated_antibody_table
    antibody_output_tables: [
      "merged_responses_antibody_swab_data",
      "antibody_merge_residuals",
      "antibody_merge_failed_records",
    ]


# SWAB -------------------------------------------------
  - function: merge_swab_ETL_a
    run: False
    swab_table: pcr_test_results
    survey_responses_table: merged_responses_antibody_data
    swab_files_to_exclude: []
    output_validated_table: outter_joined_table


  - function: merge_swab_ETL_b
    run: False
    input_joined_table: outter_joined_swab_table
    output_xtox_flagged_table: outter_joined_xtox_table


  - function: merge_swab_ETL_c
    run: False
    input_table_to_validate: outter_joined_xtox_table
    output_validated_table: validated_swab_table


  - function: merge_swab_ETL_d
    run: False
    input_table: validated_swab_table
    swab_output_tables: [
      "merged_responses_antibody_swab_data",
      "swab_merge_residuals",
      "swab_merge_failed_records",
    ]

**Comment by ohibo** [comment]
stages:
  - function: merge_blood_ETL # R3
    run: True

    # merge_blood_process_preparation
    input_antibody_table: joined_blood_test_data
    input_survey_responses_table: post_union_transformed_survey_responses
    blood_files_to_exclude: []
    output_joined_table: outter_joined_antibody_table

    # merge_blood_xtox_flag
    input_joined_table: outter_joined_antibody_table
    output_xtox_flagged_table: joined_xtox_antibody_table

    # merge_blood_process_validation
    input_table_to_validate: joined_xtox_antibody_table
    output_validated_table: validated_antibody_table

    # merge_blood_process_filtering
    input_table: validated_antibody_table
    antibody_output_tables: [
      "merged_responses_antibody_swab_data",
      "antibody_merge_residuals",
      "antibody_merge_failed_records",
    ]


  - function: merge_swab_ETL
    run: True

    # merge_swab_process_preparation
    input_swab_table: pcr_test_results
    input_survey_responses_table: merged_responses_antibody_data
    swab_files_to_exclude: []
    output_validated_table: outter_joined_swab_table

    # merge_swab_xtox_flag
    input_joined_table: outter_joined_swab_table
    output_xtox_flagged_table: outter_joined_xtox_table

    # merge_swab_process_validation
    input_table_to_validate: outter_joined_xtox_table
    output_validated_table: validated_swab_table

    # merge_swab_process_filtering
    input_table: validated_swab_table
    swab_output_tables: [
      "merged_responses_antibody_swab_data",
      "swab_merge_residuals",
      "swab_merge_failed_records",
    ]

**Comment by ohibo** [comment]
stages:
  - function: merge_blood_ETL # R3
    run: True

    input_antibody_table: joined_blood_test_data
    input_survey_responses_table: post_union_transformed_survey_responses
    blood_files_to_exclude: []
    output_joined_table: outter_joined_antibody_table

    input_joined_table: outter_joined_antibody_table
    output_xtox_flagged_table: joined_xtox_antibody_table

    input_table_to_validate: joined_xtox_antibody_table
    output_validated_table: validated_antibody_table

    input_table: validated_antibody_table
    antibody_output_tables: [
      "merged_responses_antibody_swab_data",
      "antibody_merge_residuals",
      "antibody_merge_failed_records",
    ]


  - function: merge_swab_ETL
    run: True

    input_swab_table: pcr_test_results
    input_survey_responses_table: merged_responses_antibody_data
    swab_files_to_exclude: []
    output_validated_table: outter_joined_swab_table

    input_joined_table: outter_joined_swab_table
    output_xtox_flagged_table: outter_joined_xtox_table

    input_table_to_validate: outter_joined_xtox_table
    output_validated_table: validated_swab_table

    input_table: validated_swab_table
    swab_output_tables: [
      "merged_responses_antibody_swab_data",
      "swab_merge_residuals",
      "swab_merge_failed_records",
    ]

**Review by slamothe99 — APPROVED** [review]

**Pull request merged**
